import os
import smtplib
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FutureTimeoutError
from email.message import EmailMessage
from dotenv import load_dotenv

load_dotenv()


def send_email(advisory):
    """
    Send bilingual cyclone advisory through Gmail SMTP.
    """

    email_address = os.getenv("EMAIL_ADDRESS")
    app_password = os.getenv("EMAIL_APP_PASSWORD")
    recipient = os.getenv("TEST_EMAIL")

    if not email_address:
        raise ValueError("EMAIL_ADDRESS is missing in .env")

    if not app_password:
        raise ValueError("EMAIL_APP_PASSWORD is missing in .env")

    if not recipient:
        raise ValueError("TEST_EMAIL is missing in .env")

    subject = (
        f"🚨 Cyclone Risk Advisory - "
        f"{advisory.get('risk_level', 'unknown').upper()}"
    )

    zones = advisory.get("zones", [])

    zone_text = "\n".join(
        f"- {zone}" for zone in zones
    )

    body = f"""
COASTAL RISK ADVISOR
====================

RISK LEVEL:
{advisory.get("risk_level", "unknown").upper()}

AFFECTED ZONES:
{zone_text}


ENGLISH ADVISORY:
{advisory.get("advisory_en", "")}


TAMIL ADVISORY:
{advisory.get("advisory_ta", "")}


CONFIDENCE NOTE:
{advisory.get("confidence_note", "")}


This advisory was generated by the Coastal Risk Advisor
demonstration system.
"""

    message = EmailMessage()

    message["Subject"] = subject
    message["From"] = email_address
    message["To"] = recipient

    message.set_content(body)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=8) as server:

        server.login(
            email_address,
            app_password
        )

        server.send_message(message)

    return {
        "success": True,
        "recipient": recipient,
        "channel": "email"
    }


def dispatch_advisory(advisory_json, timeout=8):
    """
    Dispatches advisory if risk level is HIGH, with a strict timeout and fallback mechanism.
    """
    if str(advisory_json.get("risk_level", "")).strip().lower() != "high":
        return {
            "success": False,
            "status": "not_dispatched",
            "message": "Risk level is not high."
        }

    try:
        with ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(send_email, advisory_json)
            result = future.result(timeout=timeout)

        return {
            "success": result.get("success", False),
            "status": "dispatched",
            "message": "Email dispatched successfully."
        }

    except FutureTimeoutError:
        return {
            "success": False,
            "status": "fallback",
            "message": f"Dispatch timed out after {timeout} seconds."
        }

    except Exception as e:
        return {
            "success": False,
            "status": "fallback",
            "message": f"Dispatch failed: {e}"
        }

